apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-collector-sa
  namespace: secops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secops
  name: log-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-reader-binding
  namespace: secops
subjects:
  - kind: ServiceAccount
    name: log-collector-sa
    namespace: secops
roleRef:
  kind: Role
  name: log-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-collector
  namespace: secops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      serviceAccountName: log-collector-sa
      containers:
        - name: log-collector
          image: rorexz/tfm@sha256:9c0bae70d6aa148ec751ede62025497f510bd4a40186c3754613bf3de47b02eb
          imagePullPolicy: Always         
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: log-collector-service
  namespace: secops
spec:
  selector:
    app: log-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

